from pygame import Color

## Screen Constants
SCREEN_WIDTH = 300
SCREEN_HEIGHT = 300
SCREEN_BACKGROUND = Color(255, 255, 255)

## Game Constants
GAME_TITLE = "NumGame 1.0"
GAME_GRID_SIZE = 3

## Button Constants
BUTTON_PADDING = 5
BUTTON_HEIGHT = (SCREEN_HEIGHT - (GAME_GRID_SIZE + 1) * BUTTON_PADDING) / GAME_GRID_SIZE
BUTTON_WIDTH = (SCREEN_WIDTH - (GAME_GRID_SIZE + 1) * BUTTON_PADDING) / GAME_GRID_SIZE
BUTTON_COLOR = Color(38, 70, 83)
BUTTON_CORRECT_COLOR = Color(141, 8, 1)
BUTTON_TEXT_COLOR = Color(255, 255, 255)
BUTTON_LAST_COLOR = Color(255, 255, 255)

## Game Completion Message
GAME_DONE_HEIGHT = 80
GAME_DONE_PADDING = 20
GAME_DONE_BACKGROUND = Color(231, 111, 81)
GAME_DONE_TEXT_COLOR = Color(0, 0, 0)
GAME_DONE_TEXT = "Game Done!"
